/* Generated By:JJTree: Do not edit this line. ASTELSECond.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Assignment3;public
class ASTELSECond extends SimpleNode {
  private String name;
  public ASTELSECond(int id) {
    super(id);
  }

  public ASTELSECond(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
  public void setName(String s) {
    this.name =s;
  }
  public String getName() {
    return this.name;
  }
}
/* JavaCC - OriginalChecksum=be04916c340c2c6c67534095f4bd7972 (do not edit this line) */
