/* Generated By:JJTree: Do not edit this line. ASTIDAssn.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Assignment3;
public class ASTIDAssn extends SimpleNode {
  private String name;
  public ASTIDAssn(int id) {
    super(id);
  }

  public ASTIDAssn(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setName(String s) {
    this.name = s;
  }
  
  public String getName() {
    return this.name;
  }
}
/* JavaCC - OriginalChecksum=f7f076b6fa636fda1ab1af352feb6385 (do not edit this line) */
