/* Generated By:JJTree: Do not edit this line. ASTLSTNComp.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Assignment3;public
class ASTLSTNComp extends SimpleNode {
  private String name;
  public ASTLSTNComp(int id) {
    super(id);
  }

  public ASTLSTNComp(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setName(String s) {
    this.name =s;
  }
  public String getName() {
    return this.name;
  }
}
/* JavaCC - OriginalChecksum=7a2f982379457c8d4250d96ca9edd02f (do not edit this line) */
