/* Generated By:JJTree: Do not edit this line. ASTPRODTerm.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Assignment3;
public
class ASTPRODTerm extends SimpleNode {
  private String name;
  public ASTPRODTerm(int id) {
    super(id);
  }

  public ASTPRODTerm(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setName(String s) {
    this.name = s;
  }

  public String getName() {
    return name;
  }
}
/* JavaCC - OriginalChecksum=4a2542a21965208f9d81bfcb3d122ddf (do not edit this line) */
