package Assignment3;

/* Generated By:JJTree: Do not edit this line. ASTSUBArith.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTSUBArith extends SimpleNode {
  private String name;
  public ASTSUBArith(int id) {
    super(id);
  }

  public ASTSUBArith(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setName(String s) {
    this.name = s;
  }

}
/* JavaCC - OriginalChecksum=1363ed61ab7bef5cb0dfa004af2c65eb (do not edit this line) */
