package Assignment3;

/* Generated By:JJTree: Do not edit this line. ASTSUMArith.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTSUMArith extends SimpleNode {
  private String name;
  public ASTSUMArith(int id) {
    super(id);
  }

  public ASTSUMArith(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }

  public void setName(String s) {
    this.name = s;
  }

  public String getName() {
    return this.name;
  }
}
/* JavaCC - OriginalChecksum=3142966308540bb5741cef236bdac09a (do not edit this line) */
