/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 6.0_1 */package Assignment3;
public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTINTID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTBOOLID node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDAssn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSUMArith node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSUBArith node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPRODTerm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIDFactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNUMFactor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEQUComp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTGRTNComp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLSTNComp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIFCond node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=75e8ce51a13df26daab7bd149f549884 (do not edit this line) */
