/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 6.0_1 */package Assignment3;
public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTINTID node, Object data);
  public Object visit(ASTBOOLID node, Object data);
  public Object visit(ASTIDAssn node, Object data);
  public Object visit(ASTSUMArith node, Object data);
  public Object visit(ASTSUBArith node, Object data);
  public Object visit(ASTPRODTerm node, Object data);
  public Object visit(ASTIDFactor node, Object data);
  public Object visit(ASTNUMFactor node, Object data);
  public Object visit(ASTEQUComp node, Object data);
  public Object visit(ASTGRTNComp node, Object data);
  public Object visit(ASTLSTNComp node, Object data);
  public Object visit(ASTIFCond node, Object data);
}
/* JavaCC - OriginalChecksum=3da51236f57c5a4f2212692ba5c3d811 (do not edit this line) */
