/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */package Assignment3;
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int BOOL = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int LBRAC = 12;
  /** RegularExpression Id. */
  int RBRAC = 13;
  /** RegularExpression Id. */
  int SUM = 14;
  /** RegularExpression Id. */
  int SUB = 15;
  /** RegularExpression Id. */
  int PROD = 16;
  /** RegularExpression Id. */
  int EQU = 17;
  /** RegularExpression Id. */
  int GRTN = 18;
  /** RegularExpression Id. */
  int LSTN = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int SEMIC = 22;
  /** RegularExpression Id. */
  int COMMA = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"int\"",
    "\"bool\"",
    "<NUM>",
    "<ID>",
    "\":=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
  };

}
