/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */package Assignment3;
public interface ParserTreeConstants
{
  public int JJTBLOCK = 0;
  public int JJTVOID = 1;
  public int JJTINTID = 2;
  public int JJTBOOLID = 3;
  public int JJTIDASSN = 4;
  public int JJTSUMARITH = 5;
  public int JJTSUBARITH = 6;
  public int JJTPRODTERM = 7;
  public int JJTIDFACTOR = 8;
  public int JJTNUMFACTOR = 9;
  public int JJTEQUCOMP = 10;
  public int JJTGRTNCOMP = 11;
  public int JJTLSTNCOMP = 12;
  public int JJTIFCOND = 13;


  public String[] jjtNodeName = {
    "Block",
    "void",
    "INTID",
    "BOOLID",
    "IDAssn",
    "SUMArith",
    "SUBArith",
    "PRODTerm",
    "IDFactor",
    "NUMFactor",
    "EQUComp",
    "GRTNComp",
    "LSTNComp",
    "IFCond",
  };
}
/* JavaCC - OriginalChecksum=243b633d7b0c293d41ad012807d429f0 (do not edit this line) */
